# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 10:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import hermes.models


class Migration(migrations.Migration):

    dependencies = [
        ("hermes", "0004_auto_20150819_2229"),
    ]

    operations = [
        migrations.CreateModel(
            name="PostFile",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "f",
                    models.FileField(
                        upload_to=hermes.models.postfile_upload_to
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="hermes.Post",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "PostFiles",
                "verbose_name": "PostFile",
            },
        ),
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=500
            ),
        ),
    ]
