# Generated by Django 2.2.24 on 2021-09-02 12:50

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hermes", "0005_auto_20170222_0421"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={
                "get_latest_by": "modified_on",
                "ordering": ("-created_on",),
            },
        ),
        migrations.AddField(
            model_name="post",
            name="tags",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=30),
                blank=True,
                default=[],
                size=None,
            ),
            preserve_default=False,
        ),
    ]
