# Generated by Django 3.2.13 on 2022-06-11 16:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("hermes", "0008_auto_20220608_1151"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="author",
            field=models.ManyToManyField(
                to=settings.AUTH_USER_MODEL, verbose_name="Authors"
            ),
        ),
    ]
