# Generated by Django 4.1.2 on 2023-01-15 18:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hermes", "0010_add_past_post_authors"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="slug",
            field=models.SlugField(
                max_length=100, unique=True, verbose_name="slug"
            ),
        ),
    ]
