# Generated by Django 4.2.16 on 2024-11-04 10:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hermes", "0012_post_hero_alt_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="hero_alt_text",
            field=models.CharField(
                blank=True,
                default="",
                max_length=100,
                verbose_name="hero alt text",
            ),
            preserve_default=False,
        ),
    ]
