# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-06 20:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backlog", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="card",
            name="labels",
        ),
        migrations.AddField(
            model_name="card",
            name="labels",
            field=models.ManyToManyField(to="backlog.CardLabel"),
        ),
    ]
