# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-07 09:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backlog", "0003_auto_20170306_2045"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="card", options={"ordering": ("weight",)},
        ),
        migrations.AddField(
            model_name="card",
            name="published",
            field=models.BooleanField(default=True),
        ),
    ]
