# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-07 09:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backlog", "0004_auto_20170307_0931"),
    ]

    operations = [
        migrations.AddField(
            model_name="card",
            name="comment_count",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
