# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-07 09:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backlog', '0005_card_comment_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='cta_url',
            field=models.URLField(blank=True, max_length=800),
        ),
        migrations.AddField(
            model_name='card',
            name='time_required',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
